# -*- coding: utf-8 -*-
"""Movie Recommendation System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cN0ZMQCPfS0es17fAowOkGTd67dUOahJ

# **Cleaning**
"""

# import needed libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#read the data

data= pd.read_csv('/content/movielens_merged.csv')
data.head(10)

#get data information

data.info()

# check the number of null values

data.isnull().sum()

#check the percentage of the messing values

missing_prc= data.isnull().mean()*100
print(missing_prc)

# check duplicated rows

data.duplicated().sum()

# 1. Drop 'tags': not needed (52.1%)
data= data.drop(['tags'], axis=1)
data.head()

# 2. Drop missing rows for 'tmdbId'
data= data.dropna(subset=['tmdbId']).copy()

# 3. Clipping for rating (in case we have rating>5, we clip it to 5)
def cap_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df[column] = df[column].clip(lower=lower, upper=upper)

# 4. Drop the 'title' column because each movie has a unique ID already so we don't need to keep the title
data= data.drop(['title'], axis=1)

# 5. Clean genres
data['genres'] = data['genres'].str.split('|')

data.head()

data.info()

# 6. Multi_Hot encoding because genre contains more than one value
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
genres_encoded = pd.DataFrame(
    mlb.fit_transform(data['genres']),
    columns=mlb.classes_,
    index=data.index
)

# combine the new columns with data and delete the old one
data = pd.concat([data.drop(columns=['genres']), genres_encoded], axis=1)

data.head()

data.info()

# Useful features
# Calculate the mean of rating for both users and movies
data['user_mean_rating'] = data.groupby('userId')['rating'].transform('mean')
data['movie_mean_rating'] = data.groupby('movieId')['rating'].transform('mean')

# Calculate the difference of rating
data['rating_diff'] = data['movie_mean_rating'] - data['user_mean_rating']

# Save Data
data.to_csv('Cleaned_Data.csv', index=False)

"""# **Vistualization**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('/content/Cleaned_Data.csv')

df.head()

df.shape

df.columns

"""Distribution of Ratings"""

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x='rating'
)

plt.title('Distribution of Movie Ratings')
plt.xlabel('Rating')
plt.ylabel('Number of Ratings')
plt.tight_layout()
plt.show()

"""Distribution of Ratings per User"""

ratings_per_user = df.groupby('userId').size()

plt.figure(figsize=(9, 5))

plt.hist(
    ratings_per_user,
    bins=30
)

plt.title('Distribution of Ratings per User')
plt.xlabel('Number of Ratings per User')
plt.ylabel('Number of Users')

plt.tight_layout()
plt.show()

"""Distribution of Ratings per Movie"""

ratings_per_movie = df.groupby('movieId').size()

plt.figure(figsize=(9, 5))

plt.hist(
    ratings_per_movie,
    bins=30
)

plt.title('Distribution of Ratings per Movie')
plt.xlabel('Number of Ratings per Movie')
plt.ylabel('Number of Movies')

plt.tight_layout()
plt.show()

"""Distribution of Average Ratings per User"""

plt.figure(figsize=(9, 5))

sns.histplot(
    df['user_mean_rating'],
    bins=30,
    kde=True
)

plt.title('Distribution of Average Ratings per User')
plt.xlabel('User Average Rating')
plt.ylabel('Number of Users')

plt.tight_layout()
plt.show()

"""Number of Ratings by Genre"""

genre_cols = [
    '(no genres listed)', 'Action', 'Adventure', 'Animation',
    'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
    'Fantasy', 'Film-Noir', 'Horror', 'IMAX', 'Musical',
    'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western'
]


genre_rating_counts = df[genre_cols].sum().sort_values(ascending=False)

plt.figure(figsize=(12, 6))

sns.barplot(
    x=genre_rating_counts.values,
    y=genre_rating_counts.index
)

plt.title('Number of Ratings by Genre')
plt.xlabel('Number of Ratings')
plt.ylabel('Genre')

plt.tight_layout()
plt.show()

"""Average Rating by Genre"""

genre_avg_rating = {}

for genre in genre_cols:
    genre_data = df[df[genre] == 1]
    genre_avg_rating[genre] = genre_data['rating'].mean()

genre_avg_rating = pd.Series(genre_avg_rating).sort_values(ascending=False)

plt.figure(figsize=(12, 6))

sns.barplot(
    x=genre_avg_rating.values,
    y=genre_avg_rating.index
)

plt.title('Average Rating by Genre')
plt.xlabel('Average Rating')
plt.ylabel('Genre')

plt.tight_layout()
plt.show()

"""Movie of Ratings vs Average Movie Rating"""

movie_stats = df.groupby('movieId')['rating'].agg(
    rating_count='count',
    average_rating='mean'
).reset_index()

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=movie_stats,
    x='rating_count',
    y='average_rating',
    alpha=0.5
)

plt.xscale('log')

plt.title('Movie Rating Count vs Average Rating (Log Scale)')
plt.xlabel('Number of Ratings (Log Scale)')
plt.ylabel('Average Rating')

plt.tight_layout()
plt.show()

"""User Average Rating Distribution"""

plt.figure(figsize=(9, 5))

sns.histplot(
    df['user_mean_rating'],
    bins=30,
    kde=True
)

plt.title('Distribution of Average Ratings per User')
plt.xlabel('User Average Rating')
plt.ylabel('Number of Users')

plt.tight_layout()
plt.show()

"""User Rating vs Movie Average Rating"""

plt.figure(figsize=(9, 6))

sns.scatterplot(
    data=df.sample(min(10000, len(df)), random_state=42),
    x='movie_mean_rating',
    y='rating',
    alpha=0.4
)

plt.title('User Rating vs Movie Average Rating')
plt.xlabel('Movie Average Rating')
plt.ylabel('User Rating')

plt.tight_layout()
plt.show()

"""Rating Difference"""

plt.figure(figsize=(9, 5))

sns.histplot(
    df['rating_diff'],
    bins=40,
    kde=True
)

plt.axvline(
    0,
    linestyle='--',
    linewidth=2
)

plt.title('Distribution of Rating Difference')
plt.xlabel('User Rating - Movie Average Rating')
plt.ylabel('Number of Ratings')

plt.tight_layout()
plt.show()

"""Most Rated Movies"""

# Load movie titles
movies = pd.read_csv('/content/movies.csv')


movie_stats = df.groupby('movieId').agg(
    rating_count=('rating', 'count'),
    average_rating=('rating', 'mean')
).reset_index()


movie_stats = movie_stats.merge(
    movies[['movieId', 'title']],
    on='movieId',
    how='left'
)

# Top 15 most-rated movies
top_movies = movie_stats.sort_values(
    'rating_count',
    ascending=False
).head(15)


plt.figure(figsize=(12, 7))

sns.barplot(
    data=top_movies,
    x='rating_count',
    y='title'
)

plt.title('Top 15 Most-Rated Movies')
plt.xlabel('Number of Ratings')
plt.ylabel('Movie')

plt.tight_layout()
plt.show()

"""User–Movie Interaction Sparsity"""

# Create User-Movie interaction matrix
user_movie_matrix = df.pivot_table(
    index='userId',
    columns='movieId',
    values='rating'
)

# Calculate sparsity
total_cells = user_movie_matrix.shape[0] * user_movie_matrix.shape[1]
observed_ratings = user_movie_matrix.notna().sum().sum()

sparsity = 1 - (observed_ratings / total_cells)

print(f"Users: {user_movie_matrix.shape[0]:,}")
print(f"Movies: {user_movie_matrix.shape[1]:,}")
print(f"Observed Ratings: {observed_ratings:,}")
print(f"Sparsity: {sparsity:.2%}")

plt.figure(figsize=(7, 5))

plt.bar(
    ['Observed Ratings', 'Missing Interactions'],
    [observed_ratings, total_cells - observed_ratings]
)

plt.title('User-Movie Interaction Sparsity')
plt.ylabel('Number of Interactions')

plt.tight_layout()
plt.show()

"""Genre Co-occurrence Heatmap"""

# Genre co-occurrence matrix
genre_matrix = df[genre_cols].T.dot(df[genre_cols])

# Remove self-co-occurrence
for genre in genre_matrix.index:
    genre_matrix.loc[genre, genre] = 0

plt.figure(figsize=(13, 10))

sns.heatmap(
    genre_matrix,
    cmap='Blues'
)

plt.title('Genre Co-occurrence Matrix')
plt.xlabel('Genre')
plt.ylabel('Genre')

plt.tight_layout()
plt.show()

"""# **Machine Learning:**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

X = data.drop(columns=['rating', 'timestamp'])
y = data['rating']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

rf_model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)


rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("--- Model Evaluation Results ---")
print(f"Random Forest RMSE: {rmse:.4f}")
print(f"Random Forest MAE:  {mae:.4f}")